name: HugoDeployOnPullRequest

on:
  pull_request:
    types: [ opened, edited ]

jobs:
  deploy:
    # "github.head_ref" returns the branch name on the pull request
    if: contains(github.head_ref, 'release') == true
    name: Create Hugo contents & Push to the release branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6]
        
    steps:

    ###
    # Initial Setup
    - name: Checkout
      uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.68.3'
    # //
    ###

    ###
    # Install Python & Library for Automatic Thumbnail Script
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install pillow via pip
      run: pip install Pillow==7.0.0
    - name: Install pyyaml via pip
      run: pip install pyyaml==5.3.1
    - name: Make deploy
      run: make deploy
    # //
    ###

    ###
    # Push to the release branch

    # To be able to push always even if there is no change
    - name: Create report file
      run: date +%s > report.txt

    - name: Commit all changes
      run: |
        ls -la
        git config --global user.email "amezousan@users.noreply.github.com"
        git config --global user.name "amezousan"
        git add --all
        git status
        git commit -m "Automated deployment"
        git push origin ${{ github.head_ref }}
    # //
    ###
