name: SyncGitrepoWithS3

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Sync git repo with AWS S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Sync files to S3 with the AWS CLI
      run: |
        export LC_ALL=en_US.UTF-8
        chmod +x ./aws_s3_sync_with_git_status.sh
        ./aws_s3_sync_with_git_status.sh -b ${{ secrets.AWS_S3_BUCKET }}